TAP_DANCE_ENABLE = yes
RGBLIGHT_ENABLE = yes
NKRO_ENABLE = yes
AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
